export const skills = [
    'TypeScript',
    'Next.js',
    'Nest.js',
    'nx.dev',
    'Docker',
    'Clojure',
    'PHP',
    'Python',
    'Firebase',
    'Supabase',
    'Appwrite',
    'GraphQL',
    'RESTful API',
]
